org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Plugin Metadata
plugin_group=net.archmon
plugin_description=A mod to bring the enderChests from Minecraft to Hytale inspired by the Minecraft mod!
plugin_author=Archmon with special thanks to Kaupenjoe
plugin_website=https://github.com/archmon/EnderStorage_By_Archmon
plugin_main_entrypoint=me.archmon.EnderStoragePlugin
server_version=2026.03.26-89796e57b
