org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Plugin Metadata
plugin_group=ExampleGroup
plugin_description=A mod to bring the enderChests from Minecraft to Hytale and inspired by the Minecraft mod of the same name.
plugin_author=Archmon with special thanks to Kaupenjoe
plugin_website=
plugin_main_entrypoint=com.example.exampleplugin.ExamplePlugin
server_version=2026.03.26-89796e57b
