org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Plugin Metadata
plugin_group=me.archmon
plugin_name=VoidStorage
plugin_description=A mod to bring the enderstorage chests from Minecraft mod to Hytale. Inspired by the Minecraft mod!
plugin_author=Archmon with special thanks to Kaupenjoe on YouTube
plugin_website=https://github.com/archmon/VoidStorage_By_Archmon/issues
plugin_main_entrypoint=me.archmon.VoidStoragePlugin
server_version=0.6.0
